[[permission]]
identifier = "allow-app-commands"
description = "Allow all application commands for both UI windows (old-ui and new-ui)."
commands.allow = [
  "all_locations",
  "has_any_visible_locations",
  "save_device_config",
  "all_instances",
  "connect",
  "disconnect",
  "update_instance",
  "location_stats",
  "location_interface_details",
  "all_connections",
  "last_connection",
  "active_connection",
  "update_location_routing",
  "delete_instance",
  "parse_tunnel_config",
  "save_tunnel",
  "all_tunnels",
  "open_link",
  "tunnel_details",
  "update_tunnel",
  "delete_tunnel",
  "get_latest_app_version",
  "start_global_logwatcher",
  "stop_global_logwatcher",
  "command_get_app_config",
  "command_set_app_config",
  "get_provisioning_config",
  "get_platform_header",
  "set_location_mfa_method",
  "open_tray_window",
  "open_full_view_window",
  "swap_to_tray",
  "swap_to_full_view",
  "close_tray_window",
  "all_active_connections",
  "disconnect_locations",
  "get_posture_data",
]
