allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  itertools: false

auditConfig:
  ignoreGhsas:
    - GHSA-wrjc-x8rr-h8h6
    - GHSA-jjmj-jmhj-qwj2
    - GHSA-337j-9hxr-rhxg
