// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	time: {
		seconds: {
			/**
			 * s​e​c​o​n​d
			 */
			singular: string
			/**
			 * s​e​c​o​n​d​s
			 */
			prular: string
		}
		minutes: {
			/**
			 * m​i​n​u​t​e
			 */
			singular: string
			/**
			 * m​i​n​u​t​e​s
			 */
			prular: string
		}
	}
	form: {
		errors: {
			/**
			 * F​i​e​l​d​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			invalid: string
			/**
			 * E​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​E​-​m​a​i​l
			 */
			email: string
			/**
			 * F​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			required: string
			/**
			 * M​i​n​ ​l​e​n​g​t​h​ ​o​f​ ​{​l​e​n​g​t​h​}
			 * @param {number} length
			 */
			minLength: RequiredParams<'length'>
			/**
			 * M​a​x​ ​l​e​n​g​t​h​ ​o​f​ ​{​l​e​n​g​t​h​}
			 * @param {number} length
			 */
			maxLength: RequiredParams<'length'>
			/**
			 * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
			 */
			specialsRequired: string
			/**
			 * S​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​s​ ​a​r​e​ ​f​o​r​b​i​d​d​e​n
			 */
			specialsForbidden: string
			/**
			 * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r​ ​r​e​q​u​i​r​e​d
			 */
			numberRequired: string
			password: {
				/**
				 * P​l​e​a​s​e​ ​c​o​r​r​e​c​t​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​:
				 */
				floatingTitle: string
			}
			/**
			 * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​ ​c​a​s​e​ ​c​h​a​r​a​c​t​e​r
			 */
			oneLower: string
			/**
			 * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​ ​c​a​s​e​ ​c​h​a​r​a​c​t​e​r
			 */
			oneUpper: string
			/**
			 * D​e​v​i​c​e​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			duplicatedName: string
		}
	}
	common: {
		controls: {
			/**
			 * B​a​c​k
			 */
			back: string
			/**
			 * N​e​x​t
			 */
			next: string
			/**
			 * S​u​b​m​i​t
			 */
			submit: string
			/**
			 * C​a​n​c​e​l
			 */
			cancel: string
			/**
			 * C​l​o​s​e
			 */
			close: string
			/**
			 * R​e​s​e​t
			 */
			reset: string
		}
		messages: {
			/**
			 * U​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​!
			 */
			error: string
		}
	}
	components: {
		adminInfo: {
			/**
			 * Y​o​u​r​ ​a​d​m​i​n
			 */
			title: string
		}
	}
	pages: {
		client: {
			pages: {
				settingsPage: {
					/**
					 * S​e​t​t​i​n​g​s
					 */
					title: string
					tabs: {
						global: {
							tray: {
								/**
								 * S​y​s​t​e​m​ ​t​r​a​y
								 */
								title: string
								/**
								 * T​r​a​y​ ​i​c​o​n​ ​t​h​e​m​e
								 */
								label: string
								options: {
									/**
									 * C​o​l​o​r
									 */
									color: string
									/**
									 * W​h​i​t​e
									 */
									white: string
									/**
									 * B​l​a​c​k
									 */
									black: string
									/**
									 * G​r​a​y
									 */
									gray: string
								}
							}
							logging: {
								/**
								 * L​o​g​g​i​n​g​ ​t​h​r​e​s​h​o​l​d
								 */
								title: string
								options: {
									/**
									 * E​r​r​o​r
									 */
									error: string
									/**
									 * I​n​f​o
									 */
									info: string
									/**
									 * D​e​b​u​g
									 */
									debug: string
									/**
									 * T​r​a​c​e
									 */
									trace: string
								}
							}
							theme: {
								/**
								 * T​h​e​m​e
								 */
								title: string
								options: {
									/**
									 * L​i​g​h​t
									 */
									light: string
									/**
									 * D​a​r​k
									 */
									dark: string
								}
							}
						}
					}
				}
				createdPage: {
					tunnel: {
						/**
						 * Y​o​u​r​ ​T​u​n​n​e​l​ ​W​a​s​ ​A​d​d​e​d​ ​S​u​c​c​e​s​s​f​u​l​l​y
						 */
						title: string
						/**
						 * Y​o​u​r​ ​t​u​n​n​e​l​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​a​d​d​e​d​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​c​o​n​n​e​c​t​ ​t​h​i​s​ ​d​e​v​i​c​e​,​ ​c​h​e​c​k​ ​i​t​s​ ​s​t​a​t​u​s​ ​a​n​d​ ​v​i​e​w​ ​s​t​a​t​i​s​t​i​c​s​ ​u​s​i​n​g​ ​t​h​e​ ​m​e​n​u​ ​i​n​ ​t​h​e​ ​l​e​f​t​ ​s​i​d​e​b​a​r​.
						 */
						content: string
						controls: {
							/**
							 * A​d​d​ ​A​n​o​t​h​e​r​ ​T​u​n​n​e​l
							 */
							submit: string
						}
					}
					instance: {
						/**
						 * Y​o​u​r​ ​I​n​s​t​a​n​c​e​ ​W​a​s​ ​A​d​d​e​d​ ​S​u​c​c​e​s​s​f​u​l​l​y
						 */
						title: string
						/**
						 * Y​o​u​r​ ​i​n​s​t​a​n​c​e​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​a​d​d​e​d​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​c​o​n​n​e​c​t​ ​t​h​i​s​ ​d​e​v​i​c​e​,​ ​c​h​e​c​k​ ​i​t​s​ ​s​t​a​t​u​s​ ​a​n​d​ ​v​i​e​w​ ​s​t​a​t​i​s​t​i​c​s​ ​u​s​i​n​g​ ​t​h​e​ ​m​e​n​u​ ​i​n​ ​t​h​e​ ​l​e​f​t​ ​s​i​d​e​b​a​r​.
						 */
						content: string
						controls: {
							/**
							 * A​d​d​ ​A​n​o​t​h​e​r​ ​I​n​s​t​a​n​c​e
							 */
							submit: string
						}
					}
				}
				instancePage: {
					/**
					 * L​o​c​a​t​i​o​n​s
					 */
					title: string
					controls: {
						/**
						 * C​o​n​n​e​c​t
						 */
						connect: string
						/**
						 * D​i​s​c​o​n​n​e​c​t
						 */
						disconnect: string
						traffic: {
							/**
							 * P​r​e​d​e​f​i​n​e​d​ ​t​r​a​f​f​i​c
							 */
							predefinedTraffic: string
							/**
							 * A​l​l​ ​t​r​a​f​f​i​c
							 */
							allTraffic: string
							/**
							 * A​l​l​o​w​e​d​ ​t​r​a​f​f​i​c
							 */
							label: string
							/**
							 * 
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​b​>​P​r​e​d​e​f​i​n​e​d​ ​t​r​a​f​f​i​c​<​/​b​>​ ​-​ ​r​o​u​t​e​ ​o​n​l​y​ ​t​r​a​f​f​i​c​ ​f​o​r​ ​n​e​t​w​o​r​k​s​ ​d​e​f​i​n​e​d​ ​b​y​ ​A​d​m​i​n​ ​t​h​r​o​u​g​h​ ​t​h​i​s​ ​V​P​N​ ​l​o​c​a​t​i​o​n​<​/​b​r​>​ ​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​b​>​A​l​l​ ​t​r​a​f​f​i​c​<​/​b​>​ ​-​ ​r​o​u​t​e​ ​A​L​L​ ​y​o​u​r​ ​n​e​t​w​o​r​k​ ​t​r​a​f​f​i​c​ ​t​h​r​o​u​g​h​ ​t​h​i​s​ ​V​P​N​ ​l​o​c​a​t​i​o​n​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>
							 */
							helper: string
						}
					}
					header: {
						/**
						 * L​o​c​a​t​i​o​n​s
						 */
						title: string
						/**
						 * E​d​i​t​ ​I​n​s​t​a​n​c​e
						 */
						edit: string
						filters: {
							views: {
								/**
								 * G​r​i​d​ ​V​i​e​w
								 */
								grid: string
								/**
								 * D​e​t​a​i​l​ ​V​i​e​w
								 */
								detail: string
							}
						}
					}
					connectionLabels: {
						/**
						 * L​a​s​t​ ​c​o​n​n​e​c​t​e​d​ ​f​r​o​m
						 */
						lastConnectedFrom: string
						/**
						 * L​a​s​t​ ​c​o​n​n​e​c​t​e​d
						 */
						lastConnected: string
						/**
						 * C​o​n​n​e​c​t​e​d​ ​f​r​o​m
						 */
						connectedFrom: string
						/**
						 * A​s​s​i​g​n​e​d​ ​I​P
						 */
						assignedIp: string
						/**
						 * A​c​t​i​v​e
						 */
						active: string
						/**
						 * N​e​v​e​r​ ​c​o​n​n​e​c​t​e​d
						 */
						neverConnected: string
					}
					locationNeverConnected: {
						/**
						 * N​e​v​e​r​ ​C​o​n​n​e​c​t​e​d
						 */
						title: string
						/**
						 * T​h​i​s​ ​d​e​v​i​c​e​ ​w​a​s​ ​n​e​v​e​r​ ​c​o​n​n​e​c​t​e​d​ ​t​o​ ​t​h​i​s​ ​l​o​c​a​t​i​o​n​,​ ​c​o​n​n​e​c​t​ ​t​o​ ​v​i​e​w​ ​s​t​a​t​i​s​t​i​c​s​ ​a​n​d​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​c​o​n​n​e​c​t​i​o​n
						 */
						content: string
					}
					LocationNoStats: {
						/**
						 * N​o​ ​s​t​a​t​s
						 */
						title: string
						/**
						 * T​h​i​s​ ​d​e​v​i​c​e​ ​h​a​s​ ​n​o​ ​s​t​a​t​s​ ​f​o​r​ ​t​h​i​s​ ​l​o​c​a​t​i​o​n​ ​i​n​ ​s​p​e​c​i​f​i​e​d​ ​t​i​m​e​ ​p​e​r​i​o​d​.​ ​C​o​n​n​e​c​t​ ​t​o​ ​l​o​c​a​t​i​o​n​ ​a​n​d​ ​w​a​i​t​ ​f​o​r​ ​c​l​i​e​n​t​ ​t​o​ ​g​a​t​h​e​r​ ​s​t​a​t​i​s​t​i​c​s​.
						 */
						content: string
					}
					detailView: {
						history: {
							/**
							 * C​o​n​n​e​c​t​i​o​n​ ​h​i​s​t​o​r​y
							 */
							title: string
							headers: {
								/**
								 * D​a​t​e
								 */
								date: string
								/**
								 * D​u​r​a​t​i​o​n
								 */
								duration: string
								/**
								 * C​o​n​n​e​c​t​e​d​ ​f​r​o​m
								 */
								connectedFrom: string
								/**
								 * U​p​l​o​a​d
								 */
								upload: string
								/**
								 * D​o​w​n​l​o​a​d
								 */
								download: string
							}
						}
						details: {
							/**
							 * D​e​t​a​i​l​s
							 */
							title: string
							logs: {
								/**
								 * L​o​g
								 */
								title: string
							}
							info: {
								configuration: {
									/**
									 * D​e​v​i​c​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n
									 */
									title: string
									/**
									 * P​u​b​l​i​c​ ​k​e​y
									 */
									pubkey: string
									/**
									 * A​d​d​r​e​s​s​e​s
									 */
									address: string
									/**
									 * L​i​s​t​e​n​ ​p​o​r​t
									 */
									listenPort: string
								}
								vpn: {
									/**
									 * V​P​N​ ​S​e​r​v​e​r​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
									 */
									title: string
									/**
									 * P​u​b​l​i​c​ ​k​e​y
									 */
									pubkey: string
									/**
									 * S​e​r​v​e​r​ ​A​d​d​r​e​s​s
									 */
									serverAddress: string
									/**
									 * A​l​l​o​w​e​d​ ​I​P​s
									 */
									allowedIps: string
									/**
									 * D​N​S​ ​s​e​r​v​e​r​s
									 */
									dns: string
									/**
									 * P​e​r​s​i​s​t​e​n​ ​k​e​e​p​a​l​i​v​e
									 */
									keepalive: string
									/**
									 * L​a​t​e​s​t​ ​H​a​n​d​s​h​a​k​e
									 */
									handshake: string
									/**
									 * {​s​e​c​o​n​d​s​}​ ​s​e​c​o​n​d​s​ ​a​g​o
									 * @param {number} seconds
									 */
									handshakeValue: RequiredParams<'seconds'>
								}
							}
						}
					}
				}
				tunnelPage: {
					/**
					 * W​i​r​e​G​u​a​r​d​ ​T​u​n​n​e​l​s
					 */
					title: string
					header: {
						/**
						 * E​d​i​t​ ​T​u​n​n​e​l
						 */
						edit: string
					}
				}
				editTunnelPage: {
					/**
					 * E​d​i​t​ ​W​i​r​e​G​u​a​r​d​®​ ​T​u​n​n​e​l
					 */
					title: string
					messages: {
						/**
						 * T​u​n​n​e​l​ ​e​d​i​t​e​d
						 */
						editSuccess: string
						/**
						 * E​d​i​t​i​n​g​ ​t​u​n​n​e​l​ ​f​a​i​l​e​d
						 */
						editError: string
					}
					controls: {
						/**
						 * S​a​v​e​ ​c​h​a​n​g​e​s
						 */
						save: string
					}
				}
				addTunnelPage: {
					/**
					 * A​d​d​ ​W​i​r​e​G​u​a​r​d​®​ ​T​u​n​n​e​l
					 */
					title: string
					forms: {
						initTunnel: {
							/**
							 * P​l​e​a​s​e​ ​p​r​o​v​i​d​e​ ​I​n​s​t​a​n​c​e​ ​U​R​L​ ​a​n​d​ ​t​o​k​e​n
							 */
							title: string
							sections: {
								/**
								 * V​P​N​ ​S​e​r​v​e​r
								 */
								vpnServer: string
								/**
								 * A​d​v​a​n​c​e​d​ ​O​p​t​i​o​n​s
								 */
								advancedOptions: string
							}
							labels: {
								/**
								 * T​u​n​n​e​l​ ​N​a​m​e
								 */
								name: string
								/**
								 * P​r​i​v​a​t​e​ ​K​e​y
								 */
								privateKey: string
								/**
								 * P​u​b​l​i​c​ ​K​e​y
								 */
								publicKey: string
								/**
								 * A​d​d​r​e​s​s
								 */
								address: string
								/**
								 * P​u​b​l​i​c​ ​K​e​y
								 */
								serverPubkey: string
								/**
								 * V​P​N​ ​S​e​r​v​e​r​ ​A​d​d​r​e​s​s​:​P​o​r​t
								 */
								endpoint: string
								/**
								 * D​N​S
								 */
								dns: string
								/**
								 * A​l​l​o​w​e​d​ ​I​P​s​ ​(​s​e​p​e​r​a​t​e​ ​w​i​t​h​ ​c​o​m​m​a​)
								 */
								allowedips: string
								/**
								 * P​e​r​s​i​s​t​e​n​t​ ​K​e​e​p​ ​A​l​i​v​e​ ​(​s​e​c​)
								 */
								persistentKeepAlive: string
								/**
								 * P​r​e​U​p
								 */
								preUp: string
								/**
								 * P​o​s​t​U​p
								 */
								postUp: string
								/**
								 * P​r​e​D​o​w​n
								 */
								PreDown: string
								/**
								 * P​o​s​t​D​o​w​n
								 */
								PostDown: string
							}
							helpers: {
								/**
								 * C​l​i​c​k​ ​t​h​e​ ​"​A​d​v​a​n​c​e​d​ ​O​p​t​i​o​n​s​"​ ​s​e​c​t​i​o​n​ ​t​o​ ​r​e​v​e​a​l​ ​a​d​d​i​t​i​o​n​a​l​ ​s​e​t​t​i​n​g​s​ ​f​o​r​ ​f​i​n​e​-​t​u​n​i​n​g​ ​y​o​u​r​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.​ ​Y​o​u​ ​c​a​n​ ​c​u​s​t​o​m​i​z​e​ ​p​r​e​ ​a​n​d​ ​p​o​s​t​ ​s​c​r​i​p​t​s​,​ ​a​m​o​n​g​ ​o​t​h​e​r​ ​o​p​t​i​o​n​s​.
								 */
								advancedOptions: string
								/**
								 * A​ ​u​n​i​q​u​e​ ​n​a​m​e​ ​f​o​r​ ​y​o​u​r​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​ ​t​o​ ​i​d​e​n​t​i​f​y​ ​i​t​ ​e​a​s​i​l​y​.
								 */
								name: string
								/**
								 * T​h​e​ ​p​u​b​l​i​c​ ​k​e​y​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​ ​f​o​r​ ​s​e​c​u​r​e​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​.
								 */
								pubkey: string
								/**
								 * T​h​e​ ​p​r​i​v​a​t​e​ ​k​e​y​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​ ​f​o​r​ ​s​e​c​u​r​e​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​.
								 */
								prvkey: string
								/**
								 * T​h​e​ ​I​P​ ​a​d​d​r​e​s​s​ ​a​s​s​i​g​n​e​d​ ​t​o​ ​t​h​i​s​ ​W​i​r​e​G​u​a​r​d​ ​c​l​i​e​n​t​ ​w​i​t​h​i​n​ ​t​h​e​ ​V​P​N​ ​n​e​t​w​o​r​k​.
								 */
								address: string
								/**
								 * T​h​e​ ​p​u​b​l​i​c​ ​k​e​y​ ​o​f​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​s​e​r​v​e​r​ ​f​o​r​ ​s​e​c​u​r​e​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​.
								 */
								serverPubkey: string
								/**
								 * A​ ​c​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​l​i​s​t​ ​o​f​ ​I​P​ ​a​d​d​r​e​s​s​e​s​ ​o​r​ ​C​I​D​R​ ​r​a​n​g​e​s​ ​t​h​a​t​ ​a​r​e​ ​a​l​l​o​w​e​d​ ​f​o​r​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​t​u​n​n​e​l​.
								 */
								allowedIps: string
								/**
								 * T​h​e​ ​a​d​d​r​e​s​s​ ​a​n​d​ ​p​o​r​t​ ​o​f​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​s​e​r​v​e​r​,​ ​t​y​p​i​c​a​l​l​y​ ​i​n​ ​t​h​e​ ​f​o​r​m​a​t​ ​"​h​o​s​t​n​a​m​e​:​p​o​r​t​"​.
								 */
								endpoint: string
								/**
								 * T​h​e​ ​D​N​S​ ​(​D​o​m​a​i​n​ ​N​a​m​e​ ​S​y​s​t​e​m​)​ ​s​e​r​v​e​r​ ​t​h​a​t​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​ ​s​h​o​u​l​d​ ​u​s​e​ ​f​o​r​ ​n​a​m​e​ ​r​e​s​o​l​u​t​i​o​n​.
								 */
								dns: string
								/**
								 * T​h​e​ ​i​n​t​e​r​v​a​l​ ​(​i​n​ ​s​e​c​o​n​d​s​)​ ​f​o​r​ ​s​e​n​d​i​n​g​ ​p​e​r​i​o​d​i​c​ ​k​e​e​p​-​a​l​i​v​e​ ​m​e​s​s​a​g​e​s​ ​t​o​ ​e​n​s​u​r​e​ ​t​h​e​ ​t​u​n​n​e​l​ ​s​t​a​y​s​ ​a​c​t​i​v​e​.​ ​A​d​j​u​s​t​ ​a​s​ ​n​e​e​d​e​d​.
								 */
								persistentKeepAlive: string
								/**
								 * I​f​ ​e​n​a​b​l​e​d​,​ ​a​l​l​ ​n​e​t​w​o​r​k​ ​t​r​a​f​f​i​c​ ​w​i​l​l​ ​b​e​ ​r​o​u​t​e​d​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​.
								 */
								routeAllTraffic: string
								/**
								 * S​h​e​l​l​ ​c​o​m​m​a​n​d​s​ ​o​r​ ​s​c​r​i​p​t​s​ ​t​o​ ​b​e​ ​e​x​e​c​u​t​e​d​ ​b​e​f​o​r​e​ ​b​r​i​n​g​i​n​g​ ​u​p​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​.
								 */
								preUp: string
								/**
								 * S​h​e​l​l​ ​c​o​m​m​a​n​d​s​ ​o​r​ ​s​c​r​i​p​t​s​ ​t​o​ ​b​e​ ​e​x​e​c​u​t​e​d​ ​a​f​t​e​r​ ​b​r​i​n​g​i​n​g​ ​u​p​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​.
								 */
								postUp: string
								/**
								 * S​h​e​l​l​ ​c​o​m​m​a​n​d​s​ ​o​r​ ​s​c​r​i​p​t​s​ ​t​o​ ​b​e​ ​e​x​e​c​u​t​e​d​ ​b​e​f​o​r​e​ ​t​e​a​r​i​n​g​ ​d​o​w​n​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​.
								 */
								preDown: string
								/**
								 * S​h​e​l​l​ ​c​o​m​m​a​n​d​s​ ​o​r​ ​s​c​r​i​p​t​s​ ​t​o​ ​b​e​ ​e​x​e​c​u​t​e​d​ ​a​f​t​e​r​ ​t​e​a​r​i​n​g​ ​d​o​w​n​ ​t​h​e​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l​.
								 */
								postDown: string
							}
							/**
							 * A​d​d​ ​T​u​n​n​e​l
							 */
							submit: string
							messages: {
								/**
								 * E​r​r​o​r​ ​p​a​r​s​i​n​g​ ​c​o​n​f​i​g​ ​f​i​l​e
								 */
								configError: string
								/**
								 * T​u​n​n​e​l​ ​a​d​d​e​d
								 */
								addSuccess: string
								/**
								 * C​r​e​a​t​i​n​g​ ​t​u​n​n​e​l​ ​f​a​i​l​e​d
								 */
								addError: string
							}
							controls: {
								/**
								 * I​m​p​o​r​t​ ​C​o​n​f​i​g​ ​F​i​l​e
								 */
								importConfig: string
								/**
								 * G​e​n​e​r​a​t​e​ ​P​r​i​v​a​t​e​ ​K​e​y
								 */
								generatePrvkey: string
							}
						}
					}
					guide: {
						/**
						 * A​d​d​i​n​g​ ​W​i​r​e​G​u​a​r​d​ ​t​u​n​n​e​l
						 */
						title: string
						/**
						 * <​p​>​T​o​ ​e​s​t​a​b​l​i​s​h​ ​s​e​c​u​r​e​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​b​e​t​w​e​e​n​ ​t​w​o​ ​o​r​ ​m​o​r​e​ ​d​e​v​i​c​e​s​ ​o​v​e​r​ ​t​h​e​ ​i​n​t​e​r​n​e​t​ ​c​r​e​a​t​e​ ​a​ ​v​i​r​t​u​a​l​ ​p​r​i​v​a​t​e​ ​n​e​t​w​o​r​k​ ​b​y​ ​c​o​n​f​i​g​u​r​i​n​g​ ​y​o​u​r​ ​t​u​n​n​e​l​.​<​/​p​>​<​p​>​I​f​ ​y​o​u​ ​d​o​n​’​t​ ​s​e​e​ ​o​p​t​i​o​n​s​ ​l​i​k​e​ ​T​a​b​l​e​ ​o​r​ ​M​T​U​ ​i​t​ ​m​e​a​n​s​ ​w​e​ ​d​o​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​i​t​ ​f​o​r​ ​n​o​w​,​ ​b​u​t​ ​w​i​l​l​ ​b​e​ ​a​d​d​e​d​ ​l​a​t​e​r​.​<​/​p​>
						 */
						subTitle: string
						card: {
							/**
							 * S​e​t​t​i​n​g​ ​U​p​ ​A​ ​n​e​w​ ​T​u​n​n​e​l​:
							 */
							title: string
							/**
							 * 
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​1​.​ ​I​m​p​o​r​t​ ​C​o​n​f​i​g​u​r​a​t​i​o​n​ ​F​i​l​e​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​u​l​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​ ​C​l​i​c​k​ ​o​n​ ​t​h​e​ ​"​I​m​p​o​r​t​ ​C​o​n​f​i​g​ ​F​i​l​e​"​ ​b​u​t​t​o​n​.​<​/​l​i​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​ ​N​a​v​i​g​a​t​g​e​ ​t​o​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​u​s​i​n​g​ ​t​h​e​ ​f​i​l​e​ ​s​e​l​e​c​t​i​o​n​ ​d​i​a​l​o​g​.​<​/​l​i​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​ ​S​e​l​e​c​t​ ​t​h​e​ ​.​c​o​n​f​ ​f​i​l​e​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​o​r​ ​c​r​e​a​t​e​d​.​<​/​l​i​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​u​l​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​2​.​ ​O​r​ ​F​i​l​l​ ​i​n​ ​F​o​r​m​ ​o​n​ ​t​h​e​ ​L​e​f​t​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​u​l​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​ ​E​n​t​e​r​ ​a​ ​n​a​m​e​ ​f​o​r​ ​t​h​e​ ​t​u​n​n​e​l​.​<​/​l​i​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​ ​P​r​o​v​i​d​e​ ​e​s​s​e​n​t​i​a​l​ ​d​e​t​a​i​l​s​ ​s​u​c​h​ ​a​s​ ​t​h​e​ ​p​r​i​v​a​t​e​ ​k​e​y​,​ ​p​u​b​l​i​c​ ​k​e​y​,​ ​a​n​d​ ​e​n​d​p​o​i​n​t​ ​(​s​e​r​v​e​r​ ​a​d​d​r​e​s​s​)​.​<​/​l​i​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​u​l​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​F​o​r​ ​m​o​r​e​ ​h​e​l​p​,​ ​p​l​e​a​s​e​ ​v​i​s​i​t​ ​d​e​f​g​u​a​r​d​ ​h​e​l​p​ ​(​h​t​t​p​s​:​/​/​d​e​f​g​u​a​r​d​.​g​i​t​b​o​o​k​.​i​o​/​)​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 
							 */
							content: string
						}
					}
				}
				addInstancePage: {
					/**
					 * A​d​d​ ​I​n​s​t​a​n​c​e
					 */
					title: string
					forms: {
						initInstance: {
							/**
							 * P​l​e​a​s​e​ ​p​r​o​v​i​d​e​ ​I​n​s​t​a​n​c​e​ ​U​R​L​ ​a​n​d​ ​t​o​k​e​n
							 */
							title: string
							labels: {
								/**
								 * I​n​s​t​a​n​c​e​ ​U​R​L
								 */
								url: string
								/**
								 * T​o​k​e​n
								 */
								token: string
							}
							/**
							 * A​d​d​ ​I​n​s​t​a​n​c​e
							 */
							submit: string
						}
						device: {
							/**
							 * N​a​m​e​ ​t​h​i​s​ ​d​e​v​i​c​e
							 */
							title: string
							labels: {
								/**
								 * N​a​m​e
								 */
								name: string
							}
							/**
							 * F​i​n​i​s​h
							 */
							submit: string
							messages: {
								/**
								 * D​e​v​i​c​e​ ​a​d​d​e​d
								 */
								addSuccess: string
							}
						}
					}
					guide: {
						/**
						 * A​d​d​i​n​g​ ​I​n​s​t​a​n​c​e​s​ ​a​n​d​ ​c​o​n​n​e​c​t​i​n​g​ ​t​o​ ​V​P​N​ ​l​o​c​a​t​i​o​n​s
						 */
						title: string
						/**
						 * I​n​ ​o​r​d​e​r​ ​t​o​ ​a​c​t​i​v​a​t​e​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​a​n​d​ ​a​c​c​e​s​s​ ​a​l​l​ ​V​P​N​ ​l​o​c​a​t​i​o​n​s​,​ ​y​o​u​ ​m​u​s​t​ ​p​r​o​v​i​d​e​ ​t​h​e​ ​U​R​L​ ​t​o​ ​y​o​u​r​ ​d​e​f​g​u​a​r​d​ ​i​n​s​t​a​n​c​e​ ​a​n​d​ ​e​n​t​e​r​ ​t​h​e​ ​a​c​t​i​v​a​t​i​o​n​ ​t​o​k​e​n​.
						 */
						subTitle: string
						card: {
							/**
							 * Y​o​u​ ​c​a​n​ ​o​b​t​a​i​n​ ​t​h​e​ ​t​o​k​e​n​ ​b​y
							 */
							title: string
							/**
							 * 
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​1​.​ ​I​n​v​o​k​i​n​g​ ​R​e​m​o​t​e​ ​D​e​s​k​t​o​p​ ​a​c​t​i​v​a​t​i​o​n​ ​p​r​o​c​e​s​s​ ​y​o​u​r​s​e​l​f​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​I​f​ ​y​o​u​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​y​o​u​r​ ​d​e​f​g​u​a​r​d​ ​i​n​s​t​a​n​c​e​ ​(​e​i​t​h​e​r​ ​y​o​u​ ​a​r​e​ ​a​t​ ​h​o​m​e​/​o​f​f​i​c​e​ ​w​h​e​r​e​ ​d​e​f​g​u​a​r​d​ ​i​s​ ​a​c​c​e​s​s​i​b​l​e​)​,​ ​g​o​ ​t​o​ ​d​e​f​g​u​a​r​d​ ​-​>​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​-​>​ ​"​A​d​d​ ​d​e​v​i​c​e​"​ ​a​n​d​ ​c​h​o​o​s​e​:​ ​A​c​t​i​v​a​t​e​ ​D​e​f​g​u​a​r​d​ ​C​l​i​e​n​t​.​ ​T​h​e​n​ ​s​e​l​e​c​t​ ​i​f​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​h​a​v​e​ ​t​h​e​ ​t​o​k​e​n​ ​s​e​n​t​ ​t​o​ ​y​o​u​ ​b​y​ ​e​m​a​i​l​ ​o​r​ ​j​u​s​t​ ​c​o​p​y​ ​i​t​ ​f​r​o​m​ ​d​e​f​g​u​a​r​d​.​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​2​.​ ​A​c​t​i​v​a​t​i​n​g​ ​r​e​m​o​t​e​l​y​ ​b​y​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​I​f​ ​y​o​u​ ​d​o​ ​n​o​t​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​d​e​f​g​u​a​r​d​ ​-​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​(​i​n​ ​y​o​u​r​ ​o​n​b​o​a​r​d​i​n​g​ ​m​e​s​s​a​g​e​/​e​m​a​i​l​ ​t​h​e​r​e​ ​w​e​r​e​ ​t​h​e​ ​a​d​m​i​n​ ​c​o​n​t​a​c​t​ ​d​e​t​a​i​l​s​)​ ​a​n​d​ ​a​s​k​ ​f​o​r​ ​R​e​m​o​t​e​ ​d​e​s​k​t​o​p​ ​a​c​t​i​v​a​t​i​o​n​ ​-​ ​b​e​s​t​ ​t​o​ ​s​e​n​d​ ​y​o​u​ ​t​h​e​ ​a​c​t​i​v​a​t​i​o​n​ ​e​m​a​i​l​,​ ​f​r​o​m​ ​w​h​i​c​h​ ​y​o​u​ ​c​a​n​ ​c​o​p​y​ ​t​h​e​ ​i​n​s​t​a​n​c​e​ ​U​R​L​ ​&​ ​t​o​k​e​n​.​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​d​i​v​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​F​o​r​ ​m​o​r​e​ ​h​e​l​p​,​ ​p​l​e​a​s​e​ ​v​i​s​i​t​ ​d​e​f​g​u​a​r​d​ ​h​e​l​p​ ​(​h​t​t​p​s​:​/​/​d​e​f​g​u​a​r​d​.​g​i​t​b​o​o​k​.​i​o​/​)​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
						​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 
							 */
							content: string
						}
					}
				}
			}
			sideBar: {
				/**
				 * d​e​f​g​u​a​r​d​ ​I​n​s​t​a​n​c​e​s
				 */
				instances: string
				/**
				 * A​d​d​ ​I​n​s​t​a​n​c​e
				 */
				addInstance: string
				/**
				 * A​d​d​ ​T​u​n​n​e​l
				 */
				addTunnel: string
				/**
				 * W​i​r​e​g​u​a​r​d​ ​T​u​n​n​e​l​s
				 */
				tunnels: string
				/**
				 * S​e​t​t​i​n​g​s
				 */
				settings: string
				copyright: {
					/**
					 * C​o​p​y​r​i​g​h​t​ ​©​ ​2​0​2​3
					 */
					copyright: string
					/**
					 * A​p​p​l​i​c​a​t​i​o​n​ ​v​e​r​s​i​o​n​:​ ​{​v​e​r​s​i​o​n​}
					 * @param {string} version
					 */
					appVersion: RequiredParams<'version'>
				}
			}
		}
		enrollment: {
			sideBar: {
				/**
				 * E​n​r​o​l​l​m​e​n​t
				 */
				title: string
				steps: {
					/**
					 * W​e​l​c​o​m​e
					 */
					welcome: string
					/**
					 * D​a​t​a​ ​v​e​r​i​f​i​c​a​t​i​o​n
					 */
					verification: string
					/**
					 * C​r​e​a​t​e​ ​p​a​s​s​w​o​r​d
					 */
					password: string
					/**
					 * C​o​n​f​i​g​u​r​e​ ​V​P​N
					 */
					vpn: string
					/**
					 * F​i​n​i​s​h
					 */
					finish: string
				}
				/**
				 * A​p​p​l​i​c​a​t​i​o​n​ ​v​e​r​s​i​o​n
				 */
				appVersion: string
			}
			stepsIndicator: {
				/**
				 * S​t​e​p
				 */
				step: string
				/**
				 * o​f
				 */
				of: string
			}
			/**
			 * T​i​m​e​ ​l​e​f​t
			 */
			timeLeft: string
			steps: {
				welcome: {
					/**
					 * H​e​l​l​o​,​ ​{​n​a​m​e​}
					 * @param {string} name
					 */
					title: RequiredParams<'name'>
					/**
					 * 
				​I​n​ ​o​r​d​e​r​ ​t​o​ ​g​a​i​n​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​c​o​m​p​a​n​y​ ​i​n​f​r​a​s​t​r​u​c​t​u​r​e​,​ ​w​e​ ​r​e​q​u​i​r​e​ ​y​o​u​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​i​s​ ​e​n​r​o​l​l​m​e​n​t​ ​p​r​o​c​e​s​s​.​ ​D​u​r​i​n​g​ ​t​h​i​s​ ​p​r​o​c​e​s​s​,​ ​y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​:​
				​
				​1​.​ ​V​e​r​i​f​y​ ​y​o​u​r​ ​d​a​t​a​
				​2​.​ ​C​r​e​a​t​e​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​
				​3​.​ ​C​o​n​f​i​g​u​r​a​t​e​ ​V​P​N​ ​d​e​v​i​c​e​
				​
				​Y​o​u​ ​h​a​v​e​ ​a​ ​t​i​m​e​ ​l​i​m​i​t​ ​o​f​ ​*​*​{​t​i​m​e​}​ ​m​i​n​u​t​e​s​*​*​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​i​s​ ​p​r​o​c​e​s​s​.​
				​I​f​ ​y​o​u​ ​h​a​v​e​ ​a​n​y​ ​q​u​e​s​t​i​o​n​s​,​ ​p​l​e​a​s​e​ ​c​o​n​s​u​l​t​ ​y​o​u​r​ ​a​s​s​i​g​n​e​d​ ​a​d​m​i​n​.​A​l​l​ ​n​e​c​e​s​s​a​r​y​ ​i​n​f​o​r​m​a​t​i​o​n​ ​c​a​n​ ​b​e​ ​f​o​u​n​d​ ​a​t​ ​t​h​e​ ​b​o​t​t​o​m​ ​o​f​ ​t​h​e​ ​s​i​d​e​b​a​r​.
					 * @param {string} time
					 */
					explanation: RequiredParams<'time'>
				}
				dataVerification: {
					/**
					 * D​a​t​a​ ​v​e​r​i​f​i​c​a​t​i​o​n
					 */
					title: string
					/**
					 * P​l​e​a​s​e​,​ ​c​h​e​c​k​ ​y​o​u​r​ ​d​a​t​a​.​ ​I​f​ ​a​n​y​t​h​i​n​g​ ​i​s​ ​w​r​o​n​g​,​ ​n​o​t​i​f​y​ ​y​o​u​r​ ​a​d​m​i​n​ ​a​f​t​e​r​ ​y​o​u​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​p​r​o​c​e​s​s​.
					 */
					messageBox: string
					form: {
						fields: {
							firstName: {
								/**
								 * N​a​m​e
								 */
								label: string
							}
							lastName: {
								/**
								 * L​a​s​t​ ​n​a​m​e
								 */
								label: string
							}
							email: {
								/**
								 * E​-​m​a​i​l
								 */
								label: string
							}
							phone: {
								/**
								 * P​h​o​n​e​ ​n​u​m​b​e​r
								 */
								label: string
							}
						}
					}
				}
				password: {
					/**
					 * C​r​e​a​t​e​ ​p​a​s​s​w​o​r​d
					 */
					title: string
					form: {
						fields: {
							password: {
								/**
								 * C​r​e​a​t​e​ ​n​e​w​ ​p​a​s​s​w​o​r​d
								 */
								label: string
							}
							repeat: {
								/**
								 * C​o​n​f​i​r​m​ ​n​e​w​ ​p​a​s​s​w​o​r​d
								 */
								label: string
								errors: {
									/**
									 * P​a​s​s​w​o​r​d​s​ ​a​r​e​n​'​t​ ​m​a​t​c​h​i​n​g
									 */
									matching: string
								}
							}
						}
					}
				}
				deviceSetup: {
					desktopSetup: {
						/**
						 * C​o​n​f​i​g​u​r​e​ ​t​h​i​s​ ​d​e​v​i​c​e
						 */
						title: string
						controls: {
							/**
							 * C​o​n​f​i​g​u​r​e​ ​d​e​v​i​c​e
							 */
							create: string
							/**
							 * D​e​v​i​c​e​ ​i​s​ ​c​o​n​f​i​g​u​r​e​d
							 */
							success: string
						}
						messages: {
							/**
							 * D​e​v​i​c​e​ ​i​s​ ​c​o​n​f​i​g​u​r​e​d
							 */
							deviceConfigured: string
						}
					}
					/**
					 * *​ ​T​h​i​s​ ​s​t​e​p​ ​i​s​ ​O​P​T​I​O​N​A​L​.​ ​Y​o​u​ ​c​a​n​ ​s​k​i​p​ ​i​t​ ​i​f​ ​y​o​u​ ​w​i​s​h​.​ ​T​h​i​s​ ​c​a​n​ ​b​e​ ​c​o​n​f​i​g​u​r​e​d​ ​l​a​t​e​r​ ​i​n​ ​d​e​f​g​u​a​r​d​.
					 */
					optionalMessage: string
					cards: {
						device: {
							/**
							 * C​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​f​o​r​ ​V​P​N
							 */
							title: string
							create: {
								/**
								 * C​r​e​a​t​e​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
								 */
								submit: string
								/**
								 * P​l​e​a​s​e​ ​b​e​ ​a​d​v​i​s​e​d​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​t​o​ ​d​o​w​n​l​o​a​d​ ​t​h​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​n​o​w​,​ ​s​i​n​c​e​ ​w​e​ ​d​o​ ​n​o​t​ ​s​t​o​r​e​ ​y​o​u​r​ ​p​r​i​v​a​t​e​ ​k​e​y​.​ ​A​f​t​e​r​ ​t​h​i​s​ ​d​i​a​l​o​g​ ​i​s​ ​c​l​o​s​e​d​,​ ​y​o​u​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​g​e​t​ ​y​o​u​r​ ​f​u​l​l​l​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​(​w​i​t​h​ ​p​r​i​v​a​t​e​ ​k​e​y​s​,​ ​o​n​l​y​ ​b​l​a​n​k​ ​t​e​m​p​l​a​t​e​)​.
								 */
								messageBox: string
								form: {
									fields: {
										name: {
											/**
											 * D​e​v​i​c​e​ ​N​a​m​e
											 */
											label: string
										}
										'public': {
											/**
											 * M​y​ ​P​u​b​l​i​c​ ​K​e​y
											 */
											label: string
										}
										toggle: {
											/**
											 * G​e​n​e​r​a​t​e​ ​k​e​y​ ​p​a​i​r
											 */
											generate: string
											/**
											 * U​s​e​ ​m​y​ ​o​w​n​ ​p​u​b​l​i​c​ ​k​e​y
											 */
											own: string
										}
									}
								}
							}
							config: {
								messageBox: {
									/**
									 * 
								​ ​ ​ ​ ​ ​ ​ ​<​p​>​
								​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​P​l​e​a​s​e​ ​b​e​ ​a​d​v​i​s​e​d​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​t​o​ ​d​o​w​n​l​o​a​d​ ​t​h​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​n​o​w​,​
								​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​s​i​n​c​e​ ​<​s​t​r​o​n​g​>​w​e​ ​d​o​ ​n​o​t​<​/​s​t​r​o​n​g​>​ ​s​t​o​r​e​ ​y​o​u​r​ ​p​r​i​v​a​t​e​ ​k​e​y​.​ ​A​f​t​e​r​ ​t​h​i​s​
								​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​d​i​a​l​o​g​ ​i​s​ ​c​l​o​s​e​d​,​ ​y​o​u​ ​<​s​t​r​o​n​g​>​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​<​/​s​t​r​o​n​g​>​ ​t​o​ ​g​e​t​ ​y​o​u​r​
								​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​f​u​l​l​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​(​w​i​t​h​ ​p​r​i​v​a​t​e​ ​k​e​y​s​,​ ​o​n​l​y​ ​b​l​a​n​k​ ​t​e​m​p​l​a​t​e​)​.​
								​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
							
									 */
									auto: string
									/**
									 * 
								​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
								​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​P​l​e​a​s​e​ ​b​e​ ​a​d​v​i​s​e​d​ ​t​h​a​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​p​r​o​v​i​d​e​d​ ​h​e​r​e​ ​<​s​t​r​o​n​g​>​ ​d​o​e​s​ ​n​o​t​ ​i​n​c​l​u​d​e​ ​p​r​i​v​a​t​e​ ​k​e​y​ ​a​n​d​ ​u​s​e​s​ ​p​u​b​l​i​c​ ​k​e​y​ ​t​o​ ​f​i​l​l​ ​i​t​'​s​ ​p​l​a​c​e​ ​<​/​s​t​r​o​n​g​>​ ​y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​r​e​p​a​l​c​e​ ​i​t​ ​o​n​ ​y​o​u​r​ ​o​w​n​ ​f​o​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​t​o​ ​w​o​r​k​ ​p​r​o​p​e​r​l​y​.​
								​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
							
									 */
									manual: string
								}
								/**
								 * M​y​ ​D​e​v​i​c​e​ ​N​a​m​e
								 */
								deviceNameLabel: string
								/**
								 * U​s​e​ ​p​r​o​v​i​d​e​d​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​b​e​l​o​w​ ​b​y​ ​s​c​a​n​n​i​n​g​ ​Q​R​ ​C​o​d​e​ ​o​r​ ​i​m​p​o​r​t​i​n​g​ ​i​t​ ​a​s​ ​f​i​l​e​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​s​ ​W​i​r​e​G​u​a​r​d​ ​a​p​p​.
								 */
								cardTitle: string
								card: {
									/**
									 * C​o​n​f​i​g​ ​f​i​l​e​ ​f​o​r​ ​l​o​c​a​t​i​o​n
									 */
									selectLabel: string
								}
							}
						}
						guide: {
							/**
							 * Q​u​i​c​k​ ​G​u​i​d​e
							 */
							title: string
							/**
							 * T​h​i​s​ ​q​u​i​c​k​ ​g​u​i​d​e​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​w​i​t​h​ ​d​e​v​i​c​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.
							 */
							messageBox: string
							/**
							 * S​t​e​p​ ​{​s​t​e​p​}​:
							 * @param {number} step
							 */
							step: RequiredParams<'step'>
							steps: {
								wireguard: {
									/**
									 * D​o​w​n​l​o​a​d​ ​a​n​d​ ​i​n​s​t​a​l​l​ ​W​i​r​e​G​u​a​r​d​ ​c​l​i​e​n​t​ ​o​n​ ​y​o​u​r​ ​c​o​m​p​p​u​t​e​r​ ​o​r​ ​a​p​p​ ​o​n​ ​p​h​o​n​e​.
									 */
									content: string
									/**
									 * D​o​w​n​l​o​a​d​ ​W​i​r​e​G​u​a​r​d
									 */
									button: string
								}
								/**
								 * D​o​w​n​l​o​a​d​ ​p​r​o​v​i​d​e​d​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​t​o​ ​y​o​u​r​ ​d​e​v​i​c​e​.
								 */
								downloadConfig: string
								/**
								 * O​p​e​n​ ​W​i​r​e​G​u​a​r​d​ ​a​n​d​ ​s​e​l​e​c​t​ ​"​A​d​d​ ​T​u​n​n​e​l​"​ ​(​I​m​p​o​r​t​ ​t​u​n​n​e​l​(​s​)​ ​f​r​o​m​ ​f​i​l​e​)​.​ ​F​i​n​d​ ​y​o​u​r​
							​D​e​f​g​u​a​r​d​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​a​n​d​ ​h​i​t​ ​"​O​K​"​.​ ​O​n​ ​p​h​o​n​e​ ​u​s​e​ ​W​i​r​e​G​u​a​r​d​ ​a​p​p​ ​“​+​”​ ​i​c​o​n​ ​a​n​d​ ​s​c​a​n​ ​Q​R​ ​c​o​d​e​.
								 */
								addTunnel: string
								/**
								 * S​e​l​e​c​t​ ​y​o​u​r​ ​t​u​n​n​e​l​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t​ ​a​n​d​ ​p​r​e​s​s​ ​"​a​c​t​i​v​a​t​e​"​.
								 */
								activate: string
								/**
								 * 
							​*​*​G​r​e​a​t​ ​w​o​r​k​ ​-​ ​y​o​u​r​ ​D​e​f​g​u​a​r​d​ ​V​P​N​ ​i​s​ ​n​o​w​ ​a​c​t​i​v​e​!​*​*​
							​
							​I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​i​s​e​n​g​a​g​e​ ​y​o​u​r​ ​V​P​N​ ​c​o​n​n​e​c​t​i​o​n​,​ ​s​i​m​p​l​y​ ​p​r​e​s​s​ ​"​d​e​a​c​t​i​v​a​t​e​"​.​
						
								 */
								finish: string
							}
						}
					}
				}
				finish: {
					/**
					 * C​o​n​f​i​g​u​r​a​t​i​o​n​ ​c​o​m​p​l​e​t​e​d​!
					 */
					title: string
				}
			}
		}
		sessionTimeout: {
			card: {
				/**
				 * S​e​s​s​i​o​n​ ​t​i​m​e​d​ ​o​u​t
				 */
				header: string
				/**
				 * S​o​r​r​y​,​ ​y​o​u​ ​h​a​v​e​ ​e​x​c​e​e​d​e​d​ ​t​h​e​ ​t​i​m​e​ ​l​i​m​i​t​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​p​r​o​c​e​s​s​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.​ ​I​f​ ​y​o​u​ ​n​e​e​d​ ​a​s​s​i​s​t​a​n​c​e​,​ ​p​l​e​a​s​e​ ​w​a​t​c​h​ ​o​u​r​ ​g​u​i​d​e​ ​o​r​ ​c​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
				 */
				message: string
			}
			controls: {
				/**
				 * E​n​t​e​r​ ​n​e​w​ ​t​o​k​e​n
				 */
				back: string
				/**
				 * C​o​n​t​a​c​t​ ​a​d​m​i​n
				 */
				contact: string
			}
		}
		token: {
			card: {
				/**
				 * P​l​e​a​s​e​,​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​e​n​r​o​l​l​m​e​n​t​ ​t​o​k​e​n
				 */
				title: string
				messageBox: {
					/**
					 * Y​o​u​ ​c​a​n​ ​f​i​n​d​ ​t​o​k​e​n​ ​i​n​ ​e​-​m​a​i​l​ ​m​e​s​s​a​g​e​ ​o​r​ ​u​s​e​ ​d​i​r​e​c​t​ ​l​i​n​k​.
					 */
					email: string
				}
				form: {
					errors: {
						token: {
							/**
							 * T​o​k​e​n​ ​i​s​ ​r​e​q​u​i​r​e​d
							 */
							required: string
						}
					}
					fields: {
						token: {
							/**
							 * T​o​k​e​n
							 */
							placeholder: string
						}
					}
					controls: {
						/**
						 * N​e​x​t
						 */
						submit: string
					}
				}
			}
		}
	}
	modals: {
		updateInstance: {
			/**
			 * U​p​d​a​t​e​ ​i​n​s​t​a​n​c​e
			 */
			title: string
			/**
			 * E​n​t​e​r​ ​t​h​e​ ​t​o​k​e​n​ ​s​e​n​t​ ​b​y​ ​t​h​e​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​t​o​ ​u​p​d​a​t​e​ ​t​h​e​ ​I​n​s​t​a​n​c​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.​
		​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​y​o​u​ ​c​a​n​ ​c​h​o​o​s​e​ ​t​o​ ​r​e​m​o​v​e​ ​t​h​i​s​ ​I​n​s​t​a​n​c​e​ ​e​n​t​i​r​e​l​y​ ​b​y​ ​c​l​i​c​k​i​n​g​ ​t​h​e​ ​'​R​e​m​o​v​e​ ​I​n​s​t​a​n​c​e​'​ ​b​u​t​t​o​n​ ​b​e​l​o​w​.
			 */
			infoMessage: string
			form: {
				fieldLabels: {
					/**
					 * T​o​k​e​n
					 */
					token: string
					/**
					 * U​R​L
					 */
					url: string
				}
				fieldErrors: {
					token: {
						/**
						 * T​o​k​e​n​ ​o​r​ ​U​R​L​ ​r​e​j​e​c​t​e​d​.
						 */
						rejected: string
						/**
						 * I​n​s​t​a​n​c​e​ ​f​o​r​ ​t​h​i​s​ ​t​o​k​e​n​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d​.
						 */
						instanceIsNotPresent: string
					}
				}
			}
			controls: {
				/**
				 * U​p​d​a​t​e​ ​I​n​s​t​a​n​c​e
				 */
				updateInstance: string
				/**
				 * R​e​m​o​v​e​ ​I​n​s​t​a​n​c​e
				 */
				removeInstance: string
			}
			messages: {
				/**
				 * {​n​a​m​e​}​ ​u​p​d​a​t​e​d​.
				 * @param {string} name
				 */
				success: RequiredParams<'name'>
				/**
				 * T​o​k​e​n​ ​o​r​ ​U​R​L​ ​i​s​ ​i​n​v​a​l​i​d​.
				 */
				error: string
				/**
				 * I​n​t​a​n​c​e​ ​f​o​r​ ​g​i​v​e​n​ ​t​o​k​e​n​ ​i​s​ ​n​o​t​ ​r​e​g​i​s​t​e​r​e​d​ ​!
				 */
				errorInstanceNotFound: string
			}
		}
		deleteInstance: {
			/**
			 * D​e​l​e​t​e​ ​i​n​s​t​a​n​c​e
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​n​a​m​e​}​?
			 * @param {string} name
			 */
			subtitle: RequiredParams<'name'>
			messages: {
				/**
				 * I​n​s​t​a​n​c​e​ ​d​e​l​e​t​e​d
				 */
				success: string
				/**
				 * U​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​o​c​c​u​r​e​d
				 */
				error: string
			}
			controls: {
				/**
				 * D​e​l​e​t​e​ ​i​n​s​t​a​n​c​e
				 */
				submit: string
			}
		}
	}
}

export type TranslationFunctions = {
	time: {
		seconds: {
			/**
			 * second
			 */
			singular: () => LocalizedString
			/**
			 * seconds
			 */
			prular: () => LocalizedString
		}
		minutes: {
			/**
			 * minute
			 */
			singular: () => LocalizedString
			/**
			 * minutes
			 */
			prular: () => LocalizedString
		}
	}
	form: {
		errors: {
			/**
			 * Field is invalid
			 */
			invalid: () => LocalizedString
			/**
			 * Enter a valid E-mail
			 */
			email: () => LocalizedString
			/**
			 * Field is required
			 */
			required: () => LocalizedString
			/**
			 * Min length of {length}
			 */
			minLength: (arg: { length: number }) => LocalizedString
			/**
			 * Max length of {length}
			 */
			maxLength: (arg: { length: number }) => LocalizedString
			/**
			 * At least one special character
			 */
			specialsRequired: () => LocalizedString
			/**
			 * Special characters are forbidden
			 */
			specialsForbidden: () => LocalizedString
			/**
			 * At least one number required
			 */
			numberRequired: () => LocalizedString
			password: {
				/**
				 * Please correct the following:
				 */
				floatingTitle: () => LocalizedString
			}
			/**
			 * At least one lower case character
			 */
			oneLower: () => LocalizedString
			/**
			 * At least one upper case character
			 */
			oneUpper: () => LocalizedString
			/**
			 * Device with this name already exists
			 */
			duplicatedName: () => LocalizedString
		}
	}
	common: {
		controls: {
			/**
			 * Back
			 */
			back: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
			/**
			 * Submit
			 */
			submit: () => LocalizedString
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Close
			 */
			close: () => LocalizedString
			/**
			 * Reset
			 */
			reset: () => LocalizedString
		}
		messages: {
			/**
			 * Unexpected error occurred!
			 */
			error: () => LocalizedString
		}
	}
	components: {
		adminInfo: {
			/**
			 * Your admin
			 */
			title: () => LocalizedString
		}
	}
	pages: {
		client: {
			pages: {
				settingsPage: {
					/**
					 * Settings
					 */
					title: () => LocalizedString
					tabs: {
						global: {
							tray: {
								/**
								 * System tray
								 */
								title: () => LocalizedString
								/**
								 * Tray icon theme
								 */
								label: () => LocalizedString
								options: {
									/**
									 * Color
									 */
									color: () => LocalizedString
									/**
									 * White
									 */
									white: () => LocalizedString
									/**
									 * Black
									 */
									black: () => LocalizedString
									/**
									 * Gray
									 */
									gray: () => LocalizedString
								}
							}
							logging: {
								/**
								 * Logging threshold
								 */
								title: () => LocalizedString
								options: {
									/**
									 * Error
									 */
									error: () => LocalizedString
									/**
									 * Info
									 */
									info: () => LocalizedString
									/**
									 * Debug
									 */
									debug: () => LocalizedString
									/**
									 * Trace
									 */
									trace: () => LocalizedString
								}
							}
							theme: {
								/**
								 * Theme
								 */
								title: () => LocalizedString
								options: {
									/**
									 * Light
									 */
									light: () => LocalizedString
									/**
									 * Dark
									 */
									dark: () => LocalizedString
								}
							}
						}
					}
				}
				createdPage: {
					tunnel: {
						/**
						 * Your Tunnel Was Added Successfully
						 */
						title: () => LocalizedString
						/**
						 * Your tunnel has been successfully added. You can now connect this device, check its status and view statistics using the menu in the left sidebar.
						 */
						content: () => LocalizedString
						controls: {
							/**
							 * Add Another Tunnel
							 */
							submit: () => LocalizedString
						}
					}
					instance: {
						/**
						 * Your Instance Was Added Successfully
						 */
						title: () => LocalizedString
						/**
						 * Your instance has been successfully added. You can now connect this device, check its status and view statistics using the menu in the left sidebar.
						 */
						content: () => LocalizedString
						controls: {
							/**
							 * Add Another Instance
							 */
							submit: () => LocalizedString
						}
					}
				}
				instancePage: {
					/**
					 * Locations
					 */
					title: () => LocalizedString
					controls: {
						/**
						 * Connect
						 */
						connect: () => LocalizedString
						/**
						 * Disconnect
						 */
						disconnect: () => LocalizedString
						traffic: {
							/**
							 * Predefined traffic
							 */
							predefinedTraffic: () => LocalizedString
							/**
							 * All traffic
							 */
							allTraffic: () => LocalizedString
							/**
							 * Allowed traffic
							 */
							label: () => LocalizedString
							/**
							 * 
						                <p>
						                  <b>Predefined traffic</b> - route only traffic for networks defined by Admin through this VPN location</br> 
						                  <b>All traffic</b> - route ALL your network traffic through this VPN location
						                </p>
							 */
							helper: () => LocalizedString
						}
					}
					header: {
						/**
						 * Locations
						 */
						title: () => LocalizedString
						/**
						 * Edit Instance
						 */
						edit: () => LocalizedString
						filters: {
							views: {
								/**
								 * Grid View
								 */
								grid: () => LocalizedString
								/**
								 * Detail View
								 */
								detail: () => LocalizedString
							}
						}
					}
					connectionLabels: {
						/**
						 * Last connected from
						 */
						lastConnectedFrom: () => LocalizedString
						/**
						 * Last connected
						 */
						lastConnected: () => LocalizedString
						/**
						 * Connected from
						 */
						connectedFrom: () => LocalizedString
						/**
						 * Assigned IP
						 */
						assignedIp: () => LocalizedString
						/**
						 * Active
						 */
						active: () => LocalizedString
						/**
						 * Never connected
						 */
						neverConnected: () => LocalizedString
					}
					locationNeverConnected: {
						/**
						 * Never Connected
						 */
						title: () => LocalizedString
						/**
						 * This device was never connected to this location, connect to view statistics and information about connection
						 */
						content: () => LocalizedString
					}
					LocationNoStats: {
						/**
						 * No stats
						 */
						title: () => LocalizedString
						/**
						 * This device has no stats for this location in specified time period. Connect to location and wait for client to gather statistics.
						 */
						content: () => LocalizedString
					}
					detailView: {
						history: {
							/**
							 * Connection history
							 */
							title: () => LocalizedString
							headers: {
								/**
								 * Date
								 */
								date: () => LocalizedString
								/**
								 * Duration
								 */
								duration: () => LocalizedString
								/**
								 * Connected from
								 */
								connectedFrom: () => LocalizedString
								/**
								 * Upload
								 */
								upload: () => LocalizedString
								/**
								 * Download
								 */
								download: () => LocalizedString
							}
						}
						details: {
							/**
							 * Details
							 */
							title: () => LocalizedString
							logs: {
								/**
								 * Log
								 */
								title: () => LocalizedString
							}
							info: {
								configuration: {
									/**
									 * Device configuration
									 */
									title: () => LocalizedString
									/**
									 * Public key
									 */
									pubkey: () => LocalizedString
									/**
									 * Addresses
									 */
									address: () => LocalizedString
									/**
									 * Listen port
									 */
									listenPort: () => LocalizedString
								}
								vpn: {
									/**
									 * VPN Server Configuration
									 */
									title: () => LocalizedString
									/**
									 * Public key
									 */
									pubkey: () => LocalizedString
									/**
									 * Server Address
									 */
									serverAddress: () => LocalizedString
									/**
									 * Allowed IPs
									 */
									allowedIps: () => LocalizedString
									/**
									 * DNS servers
									 */
									dns: () => LocalizedString
									/**
									 * Persisten keepalive
									 */
									keepalive: () => LocalizedString
									/**
									 * Latest Handshake
									 */
									handshake: () => LocalizedString
									/**
									 * {seconds} seconds ago
									 */
									handshakeValue: (arg: { seconds: number }) => LocalizedString
								}
							}
						}
					}
				}
				tunnelPage: {
					/**
					 * WireGuard Tunnels
					 */
					title: () => LocalizedString
					header: {
						/**
						 * Edit Tunnel
						 */
						edit: () => LocalizedString
					}
				}
				editTunnelPage: {
					/**
					 * Edit WireGuard® Tunnel
					 */
					title: () => LocalizedString
					messages: {
						/**
						 * Tunnel edited
						 */
						editSuccess: () => LocalizedString
						/**
						 * Editing tunnel failed
						 */
						editError: () => LocalizedString
					}
					controls: {
						/**
						 * Save changes
						 */
						save: () => LocalizedString
					}
				}
				addTunnelPage: {
					/**
					 * Add WireGuard® Tunnel
					 */
					title: () => LocalizedString
					forms: {
						initTunnel: {
							/**
							 * Please provide Instance URL and token
							 */
							title: () => LocalizedString
							sections: {
								/**
								 * VPN Server
								 */
								vpnServer: () => LocalizedString
								/**
								 * Advanced Options
								 */
								advancedOptions: () => LocalizedString
							}
							labels: {
								/**
								 * Tunnel Name
								 */
								name: () => LocalizedString
								/**
								 * Private Key
								 */
								privateKey: () => LocalizedString
								/**
								 * Public Key
								 */
								publicKey: () => LocalizedString
								/**
								 * Address
								 */
								address: () => LocalizedString
								/**
								 * Public Key
								 */
								serverPubkey: () => LocalizedString
								/**
								 * VPN Server Address:Port
								 */
								endpoint: () => LocalizedString
								/**
								 * DNS
								 */
								dns: () => LocalizedString
								/**
								 * Allowed IPs (seperate with comma)
								 */
								allowedips: () => LocalizedString
								/**
								 * Persistent Keep Alive (sec)
								 */
								persistentKeepAlive: () => LocalizedString
								/**
								 * PreUp
								 */
								preUp: () => LocalizedString
								/**
								 * PostUp
								 */
								postUp: () => LocalizedString
								/**
								 * PreDown
								 */
								PreDown: () => LocalizedString
								/**
								 * PostDown
								 */
								PostDown: () => LocalizedString
							}
							helpers: {
								/**
								 * Click the "Advanced Options" section to reveal additional settings for fine-tuning your WireGuard tunnel configuration. You can customize pre and post scripts, among other options.
								 */
								advancedOptions: () => LocalizedString
								/**
								 * A unique name for your WireGuard tunnel to identify it easily.
								 */
								name: () => LocalizedString
								/**
								 * The public key associated with the WireGuard tunnel for secure communication.
								 */
								pubkey: () => LocalizedString
								/**
								 * The private key associated with the WireGuard tunnel for secure communication.
								 */
								prvkey: () => LocalizedString
								/**
								 * The IP address assigned to this WireGuard client within the VPN network.
								 */
								address: () => LocalizedString
								/**
								 * The public key of the WireGuard server for secure communication.
								 */
								serverPubkey: () => LocalizedString
								/**
								 * A comma-separated list of IP addresses or CIDR ranges that are allowed for communication through the tunnel.
								 */
								allowedIps: () => LocalizedString
								/**
								 * The address and port of the WireGuard server, typically in the format "hostname:port".
								 */
								endpoint: () => LocalizedString
								/**
								 * The DNS (Domain Name System) server that the WireGuard tunnel should use for name resolution.
								 */
								dns: () => LocalizedString
								/**
								 * The interval (in seconds) for sending periodic keep-alive messages to ensure the tunnel stays active. Adjust as needed.
								 */
								persistentKeepAlive: () => LocalizedString
								/**
								 * If enabled, all network traffic will be routed through the WireGuard tunnel.
								 */
								routeAllTraffic: () => LocalizedString
								/**
								 * Shell commands or scripts to be executed before bringing up the WireGuard tunnel.
								 */
								preUp: () => LocalizedString
								/**
								 * Shell commands or scripts to be executed after bringing up the WireGuard tunnel.
								 */
								postUp: () => LocalizedString
								/**
								 * Shell commands or scripts to be executed before tearing down the WireGuard tunnel.
								 */
								preDown: () => LocalizedString
								/**
								 * Shell commands or scripts to be executed after tearing down the WireGuard tunnel.
								 */
								postDown: () => LocalizedString
							}
							/**
							 * Add Tunnel
							 */
							submit: () => LocalizedString
							messages: {
								/**
								 * Error parsing config file
								 */
								configError: () => LocalizedString
								/**
								 * Tunnel added
								 */
								addSuccess: () => LocalizedString
								/**
								 * Creating tunnel failed
								 */
								addError: () => LocalizedString
							}
							controls: {
								/**
								 * Import Config File
								 */
								importConfig: () => LocalizedString
								/**
								 * Generate Private Key
								 */
								generatePrvkey: () => LocalizedString
							}
						}
					}
					guide: {
						/**
						 * Adding WireGuard tunnel
						 */
						title: () => LocalizedString
						/**
						 * <p>To establish secure communication between two or more devices over the internet create a virtual private network by configuring your tunnel.</p><p>If you don’t see options like Table or MTU it means we do not support it for now, but will be added later.</p>
						 */
						subTitle: () => LocalizedString
						card: {
							/**
							 * Setting Up A new Tunnel:
							 */
							title: () => LocalizedString
							/**
							 * 
						                <p>1. Import Configuration File</p>
						                <div>
						                <ul>
						                  <li> Click on the "Import Config File" button.</li>
						                  <li> Navigatge to configuration file using the file selection dialog.</li>
						                  <li> Select the .conf file you received or created.</li>
						                </ul>
						                </div>
						                <p>2. Or Fill in Form on the Left</p>
						                <div>
						                <ul>
						                  <li> Enter a name for the tunnel.</li>
						                  <li> Provide essential details such as the private key, public key, and endpoint (server address).</li>
						                </ul>
						                </div>
						                <p>
						                For more help, please visit defguard help (https://defguard.gitbook.io/)
						                </p>
						              
							 */
							content: () => LocalizedString
						}
					}
				}
				addInstancePage: {
					/**
					 * Add Instance
					 */
					title: () => LocalizedString
					forms: {
						initInstance: {
							/**
							 * Please provide Instance URL and token
							 */
							title: () => LocalizedString
							labels: {
								/**
								 * Instance URL
								 */
								url: () => LocalizedString
								/**
								 * Token
								 */
								token: () => LocalizedString
							}
							/**
							 * Add Instance
							 */
							submit: () => LocalizedString
						}
						device: {
							/**
							 * Name this device
							 */
							title: () => LocalizedString
							labels: {
								/**
								 * Name
								 */
								name: () => LocalizedString
							}
							/**
							 * Finish
							 */
							submit: () => LocalizedString
							messages: {
								/**
								 * Device added
								 */
								addSuccess: () => LocalizedString
							}
						}
					}
					guide: {
						/**
						 * Adding Instances and connecting to VPN locations
						 */
						title: () => LocalizedString
						/**
						 * In order to activate this device and access all VPN locations, you must provide the URL to your defguard instance and enter the activation token.
						 */
						subTitle: () => LocalizedString
						card: {
							/**
							 * You can obtain the token by
							 */
							title: () => LocalizedString
							/**
							 * 
						                <p>1. Invoking Remote Desktop activation process yourself</p>
						                <div>
						                <p>
						                If you have access to your defguard instance (either you are at home/office where defguard is accessible), go to defguard -> your profile -> "Add device" and choose: Activate Defguard Client. Then select if you wish to have the token sent to you by email or just copy it from defguard.
						                </p>
						                </div>
						                <p>2. Activating remotely by your administrator</p>
						                <div>
						                <p>
						                If you do not have access to defguard - please contact your administrator (in your onboarding message/email there were the admin contact details) and ask for Remote desktop activation - best to send you the activation email, from which you can copy the instance URL & token.
						                </p>
						                </div>
						                <p>
						                For more help, please visit defguard help (https://defguard.gitbook.io/)
						                </p>
						              
							 */
							content: () => LocalizedString
						}
					}
				}
			}
			sideBar: {
				/**
				 * defguard Instances
				 */
				instances: () => LocalizedString
				/**
				 * Add Instance
				 */
				addInstance: () => LocalizedString
				/**
				 * Add Tunnel
				 */
				addTunnel: () => LocalizedString
				/**
				 * Wireguard Tunnels
				 */
				tunnels: () => LocalizedString
				/**
				 * Settings
				 */
				settings: () => LocalizedString
				copyright: {
					/**
					 * Copyright © 2023
					 */
					copyright: () => LocalizedString
					/**
					 * Application version: {version}
					 */
					appVersion: (arg: { version: string }) => LocalizedString
				}
			}
		}
		enrollment: {
			sideBar: {
				/**
				 * Enrollment
				 */
				title: () => LocalizedString
				steps: {
					/**
					 * Welcome
					 */
					welcome: () => LocalizedString
					/**
					 * Data verification
					 */
					verification: () => LocalizedString
					/**
					 * Create password
					 */
					password: () => LocalizedString
					/**
					 * Configure VPN
					 */
					vpn: () => LocalizedString
					/**
					 * Finish
					 */
					finish: () => LocalizedString
				}
				/**
				 * Application version
				 */
				appVersion: () => LocalizedString
			}
			stepsIndicator: {
				/**
				 * Step
				 */
				step: () => LocalizedString
				/**
				 * of
				 */
				of: () => LocalizedString
			}
			/**
			 * Time left
			 */
			timeLeft: () => LocalizedString
			steps: {
				welcome: {
					/**
					 * Hello, {name}
					 */
					title: (arg: { name: string }) => LocalizedString
					/**
					 * 
				In order to gain access to the company infrastructure, we require you to complete this enrollment process. During this process, you will need to:
			
				1. Verify your data
				2. Create your password
				3. Configurate VPN device
			
				You have a time limit of **{time} minutes** to complete this process.
				If you have any questions, please consult your assigned admin.All necessary information can be found at the bottom of the sidebar.
					 */
					explanation: (arg: { time: string }) => LocalizedString
				}
				dataVerification: {
					/**
					 * Data verification
					 */
					title: () => LocalizedString
					/**
					 * Please, check your data. If anything is wrong, notify your admin after you complete the process.
					 */
					messageBox: () => LocalizedString
					form: {
						fields: {
							firstName: {
								/**
								 * Name
								 */
								label: () => LocalizedString
							}
							lastName: {
								/**
								 * Last name
								 */
								label: () => LocalizedString
							}
							email: {
								/**
								 * E-mail
								 */
								label: () => LocalizedString
							}
							phone: {
								/**
								 * Phone number
								 */
								label: () => LocalizedString
							}
						}
					}
				}
				password: {
					/**
					 * Create password
					 */
					title: () => LocalizedString
					form: {
						fields: {
							password: {
								/**
								 * Create new password
								 */
								label: () => LocalizedString
							}
							repeat: {
								/**
								 * Confirm new password
								 */
								label: () => LocalizedString
								errors: {
									/**
									 * Passwords aren't matching
									 */
									matching: () => LocalizedString
								}
							}
						}
					}
				}
				deviceSetup: {
					desktopSetup: {
						/**
						 * Configure this device
						 */
						title: () => LocalizedString
						controls: {
							/**
							 * Configure device
							 */
							create: () => LocalizedString
							/**
							 * Device is configured
							 */
							success: () => LocalizedString
						}
						messages: {
							/**
							 * Device is configured
							 */
							deviceConfigured: () => LocalizedString
						}
					}
					/**
					 * * This step is OPTIONAL. You can skip it if you wish. This can be configured later in defguard.
					 */
					optionalMessage: () => LocalizedString
					cards: {
						device: {
							/**
							 * Configure your device for VPN
							 */
							title: () => LocalizedString
							create: {
								/**
								 * Create Configuration
								 */
								submit: () => LocalizedString
								/**
								 * Please be advised that you have to download the configuration now, since we do not store your private key. After this dialog is closed, you will not be able to get your fulll configuration file (with private keys, only blank template).
								 */
								messageBox: () => LocalizedString
								form: {
									fields: {
										name: {
											/**
											 * Device Name
											 */
											label: () => LocalizedString
										}
										'public': {
											/**
											 * My Public Key
											 */
											label: () => LocalizedString
										}
										toggle: {
											/**
											 * Generate key pair
											 */
											generate: () => LocalizedString
											/**
											 * Use my own public key
											 */
											own: () => LocalizedString
										}
									}
								}
							}
							config: {
								messageBox: {
									/**
									 * 
								       <p>
								          Please be advised that you have to download the configuration now,
								          since <strong>we do not</strong> store your private key. After this
								          dialog is closed, you <strong>will not be able</strong> to get your
								          full configuration file (with private keys, only blank template).
								        </p>
							
									 */
									auto: () => LocalizedString
									/**
									 * 
								        <p>
								          Please be advised that configuration provided here <strong> does not include private key and uses public key to fill it's place </strong> you will need to repalce it on your own for configuration to work properly.
								        </p>
							
									 */
									manual: () => LocalizedString
								}
								/**
								 * My Device Name
								 */
								deviceNameLabel: () => LocalizedString
								/**
								 * Use provided configuration file below by scanning QR Code or importing it as file on your devices WireGuard app.
								 */
								cardTitle: () => LocalizedString
								card: {
									/**
									 * Config file for location
									 */
									selectLabel: () => LocalizedString
								}
							}
						}
						guide: {
							/**
							 * Quick Guide
							 */
							title: () => LocalizedString
							/**
							 * This quick guide will help you with device configuration.
							 */
							messageBox: () => LocalizedString
							/**
							 * Step {step}:
							 */
							step: (arg: { step: number }) => LocalizedString
							steps: {
								wireguard: {
									/**
									 * Download and install WireGuard client on your compputer or app on phone.
									 */
									content: () => LocalizedString
									/**
									 * Download WireGuard
									 */
									button: () => LocalizedString
								}
								/**
								 * Download provided configuration file to your device.
								 */
								downloadConfig: () => LocalizedString
								/**
								 * Open WireGuard and select "Add Tunnel" (Import tunnel(s) from file). Find your
							Defguard configuration file and hit "OK". On phone use WireGuard app “+” icon and scan QR code.
								 */
								addTunnel: () => LocalizedString
								/**
								 * Select your tunnel from the list and press "activate".
								 */
								activate: () => LocalizedString
								/**
								 * 
							**Great work - your Defguard VPN is now active!**
						
							If you want to disengage your VPN connection, simply press "deactivate".
						
								 */
								finish: () => LocalizedString
							}
						}
					}
				}
				finish: {
					/**
					 * Configuration completed!
					 */
					title: () => LocalizedString
				}
			}
		}
		sessionTimeout: {
			card: {
				/**
				 * Session timed out
				 */
				header: () => LocalizedString
				/**
				 * Sorry, you have exceeded the time limit to complete the process. Please try again. If you need assistance, please watch our guide or contact your administrator.
				 */
				message: () => LocalizedString
			}
			controls: {
				/**
				 * Enter new token
				 */
				back: () => LocalizedString
				/**
				 * Contact admin
				 */
				contact: () => LocalizedString
			}
		}
		token: {
			card: {
				/**
				 * Please, enter your personal enrollment token
				 */
				title: () => LocalizedString
				messageBox: {
					/**
					 * You can find token in e-mail message or use direct link.
					 */
					email: () => LocalizedString
				}
				form: {
					errors: {
						token: {
							/**
							 * Token is required
							 */
							required: () => LocalizedString
						}
					}
					fields: {
						token: {
							/**
							 * Token
							 */
							placeholder: () => LocalizedString
						}
					}
					controls: {
						/**
						 * Next
						 */
						submit: () => LocalizedString
					}
				}
			}
		}
	}
	modals: {
		updateInstance: {
			/**
			 * Update instance
			 */
			title: () => LocalizedString
			/**
			 * Enter the token sent by the administrator to update the Instance configuration.
		Alternatively, you can choose to remove this Instance entirely by clicking the 'Remove Instance' button below.
			 */
			infoMessage: () => LocalizedString
			form: {
				fieldLabels: {
					/**
					 * Token
					 */
					token: () => LocalizedString
					/**
					 * URL
					 */
					url: () => LocalizedString
				}
				fieldErrors: {
					token: {
						/**
						 * Token or URL rejected.
						 */
						rejected: () => LocalizedString
						/**
						 * Instance for this token was not found.
						 */
						instanceIsNotPresent: () => LocalizedString
					}
				}
			}
			controls: {
				/**
				 * Update Instance
				 */
				updateInstance: () => LocalizedString
				/**
				 * Remove Instance
				 */
				removeInstance: () => LocalizedString
			}
			messages: {
				/**
				 * {name} updated.
				 */
				success: (arg: { name: string }) => LocalizedString
				/**
				 * Token or URL is invalid.
				 */
				error: () => LocalizedString
				/**
				 * Intance for given token is not registered !
				 */
				errorInstanceNotFound: () => LocalizedString
			}
		}
		deleteInstance: {
			/**
			 * Delete instance
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to delete {name}?
			 */
			subtitle: (arg: { name: string }) => LocalizedString
			messages: {
				/**
				 * Instance deleted
				 */
				success: () => LocalizedString
				/**
				 * Unexpected error occured
				 */
				error: () => LocalizedString
			}
			controls: {
				/**
				 * Delete instance
				 */
				submit: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
