[package]
name = "defguard-cli"
version = "1.0.0"
edition = "2021"
rust-version = "1.80"

[build-dependencies]
prost-build = "0.13"

[dependencies]
clap = { version = "4.5", features = ["cargo", "derive"] }
common = { path = "../common" }
defguard_wireguard_rs = { workspace = true }
dirs-next = "2.0"
prost = "0.13"
reqwest = { version = "0.12", features = ["cookies", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
x25519-dalek = { version = "2", features = [
    "getrandom",
    "serde",
    "static_secrets",
] }
