[package]
name = "defguard-cli"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["cargo", "derive"] }
common = { path = "../common" }
defguard-client = { path = ".." }
defguard_wireguard_rs = { git = "https://github.com/DefGuard/wireguard-rs.git", rev = "v0.5.5" }
dirs-next = "2.0"
reqwest = { version = "0.12", features = ["cookies", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = [
    "chrono",
    "sqlite",
    "runtime-tokio",
    "macros",
] }
thiserror = "2.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
