name: "Build Windows client"
on:
  push:
    branches:
      - fix-blocking-calls

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        windows_runner:
          - windows-latest
          - windows-11-arm
        include:
          - windows_runner: windows-latest
            cpu: x64
          - windows_runner: windows-11-arm
            cpu: arm64
    runs-on: ${{ matrix.windows_runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v5
        with:
          version: 10
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> ${GITHUB_ENV}
      - uses: actions/cache@v5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-build-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-build-store-
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        uses: tauri-apps/tauri-action@v0.5.23
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload unsigned bundle
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-bundle-${{ matrix.cpu }}
          path: src-tauri/target/release/bundle/msi/Defguard_1.6.8_${{ matrix.cpu }}_en-US.msi

  sign-bundle:
    needs:
      - build-windows
    strategy:
      fail-fast: false
      matrix:
        cpu:
          - x64
          - arm64
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Download unsigned bundle
        uses: actions/download-artifact@v4
        with:
          name: unsigned-bundle-${{ matrix.cpu }}
      - name: Sign bundle
        run: osslsigncode sign -pkcs11module /srv/codesign/certum/sc30pkcs11-3.0.6.72-MS.so -pkcs11cert ${{ secrets.CODESIGN_KEYID }} -key ${{ secrets.CODESIGN_KEYID }} -pass ${{ secrets.CODESIGN_PIN }} -h sha256 -t http://time.certum.pl/ -in Defguard_1.6.8_${{ matrix.cpu }}_en-US.msi -out Defguard-signed.msi
      - name: Rename signed bundle
        run: mv Defguard-signed.msi Defguard_1.6.8_${{ matrix.cpu }}_en-US.msi
      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: Defguard_1.6.8_${{ matrix.cpu }}_en-US
          path: Defguard_1.6.8_${{ matrix.cpu }}_en-US.msi
