name: 'lint'

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
      - dev
      - 'release/**'
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  lint-web:
    runs-on:
      - codebuild-defguard-client-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-lint-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-lint-store-

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run Biome and Prettier Lint
        run: pnpm lint

      - name: Audit
        run: pnpm audit --prod
