name: 'lint'

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
      - dev
      - 'release/**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  lint-web:
    runs-on:
      - codebuild-defguard-client-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-node@v6
        with:
          node-version: 26

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          run_install: false
          version: 11

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-lint-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-lint-store-

      # Change to '--frozen-lockfile' once this gets fixed:
      # https://github.com/pnpm/action-setup/issues/40
      - name: Install Node dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Biome and Prettier Lint
        run: pnpm lint

      # TODO: Restore when it works again: https://github.com/pnpm/pnpm/issues/11265
      # - name: Audit
      #   run: pnpm audit --prod
