name: Build DG

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of binary to archive and upload'
        required: true
        type: string
      binary_arch:
        description: 'Architecture name'
        required: true
        type: string
      system:
        description: 'Operating system name'
        required: true
        type: string
      runner:
        description: 'Runner to run this job on'
        required: true
        type: string

jobs:
  make-binary:
    runs-on:
      - self-hosted
      - Linux
      - ${{ inputs.runner }}
    steps:
      - name: Rename client binary
        run: mv src-tauri/target/release/${{ inputs.flavor }} ${{ inputs.flavor }}-${{ inputs.system }}-${{ inputs.binary_arch }}-${{ github.ref_name }}
      - name: Tar client binary
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: |
            ${{ inputs.flavor }}-${{ inputs.system }}-${{ inputs.binary_arch }}-${{ github.ref_name }}
          outPath: ${{ inputs.flavor }}-${{ inputs.system }}-${{ inputs.binary_arch }}-${{ github.ref_name }}.tar.gz
      - name: Upload client archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ inputs.flavor }}-${{ inputs.system }}-${{ inputs.binary_arch }}-${{ github.ref_name }}.tar.gz
          asset_name: ${{ inputs.flavor }}-${{ inputs.system }}-${{ inputs.binary_arch }}-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
